from copy import deepcopy

import sqlglot
from sqlglot import exp

from medalflow.constants.medallion import Layer
from medalflow.medallion.base.sequencer import _BaseSequencer
from medalflow.settings import get_settings
from medalflow.types.metadata import QueryMetadata


class SilverTransformationSequencer(_BaseSequencer):
    def __init__(self, sql_dialect: str = "tsql"):
        """Initialize the Silver Transformation sequencer.

        Args:
            sql_dialect: SQL dialect for parsing (tsql for Synapse, spark for Databricks, etc.)
        """
        settings = get_settings()
        super().__init__(settings)
        self.layer = Layer.SILVER
        # Override sql_dialect if provided
        if sql_dialect:
            self.sql_dialect = sql_dialect

    def get_layer_name(self) -> str:
        """Return the layer name for this sequencer.

        Returns:
            'silver' - the silver layer identifier
        """
        return self.layer.value

    def get_obj_name(self) -> str:
        """Get unique object name for Silver transformation sequencer.

        Returns the name from the silver metadata if available,
        otherwise falls back to class name.

        Returns:
            name from metadata or class name
        """
        metadata = self._get_class_metadata()
        if metadata and "name" in metadata:
            return metadata["name"]

        return super().get_obj_name()

    def _get_class_metadata_attribute(self) -> str | None:
        """Get the class-level metadata attribute name for Silver Transformation sequencer.

        Silver Transformation sequencer uses @silver_metadata decorator at class level.

        Returns:
            '_silver_metadata' - the attribute name for class metadata
        """
        return "_silver_metadata"

    def _handle_null_result(self, metadata: QueryMetadata) -> str | None:
        """Handle filter-based dimensions that return None.

        Auto-generates enum queries for Silver dimension tables with filter metadata.

        Args:
            metadata: Query metadata from the decorator

        Returns:
            Optional[str]: Generated enum query or None if not applicable
        """
        if hasattr(metadata, "filter") and metadata.filter:
            return self._generate_enum_query(metadata)
        return None

    def _generate_enum_query(self, metadata: QueryMetadata) -> str:
        """Generate enum query for filter-based dimensions.

        Which table holds the enums, and what its columns are called, comes
        from ``conventions.enum_table``. The schema, table and column names are
        deployment configuration and are inlined as written; the decorator's
        ``filter`` value is not, and is escaped as the string literal it is.

        Args:
            metadata: QueryMetadata with filter and table_name fields

        Returns:
            str: Auto-generated SQL query for enum lookup

        Raises:
            ValueError: If the enum-table convention is not configured
        """
        convention = self.settings.conventions.enum_table
        if convention is None:
            raise ValueError(
                f"Table '{metadata.table_name}' is declared with filter="
                f"{metadata.filter!r}, but no enum table is configured. Set "
                "MEDALFLOW_CONVENTIONS__ENUM_TABLE__{SCHEMA_NAME,TABLE_NAME,"
                "NAME_COLUMN,VALUE_COLUMN,VALUE_ID_COLUMN}, or drop the filter "
                "and return the query from the method itself."
            )

        table_name = metadata.table_name
        from medalflow.query_builder.factory import create_query_builder

        query_builder = create_query_builder()

        enum_table = query_builder.fully_qualified_name(
            convention.schema_name, convention.table_name
        )
        enum_name = query_builder.quote_string(metadata.filter)
        return f"""SELECT
                {convention.value_column} AS {table_name},
                {convention.value_id_column} AS {table_name}ID,
                CURRENT_TIMESTAMP AS _CreatedDate,
                CURRENT_TIMESTAMP AS _ModifiedDate
            FROM {enum_table}
            WHERE {convention.name_column} = {enum_name}"""

    def _transform_query_result(
        self, sql: str, metadata: QueryMetadata
    ) -> tuple[str, QueryMetadata]:
        """Promote a staged detail table into the silver layer.

        Rewriting a query's target schema *and* table name under its author is
        not something to do by default, so it happens only when
        ``conventions.detail_tables`` says which suffix and schemas mark a
        detail table. Unconfigured, the query is returned untouched.

        Args:
            sql: The SQL query string generated by the method
            metadata: Query metadata from the decorator

        Returns:
            tuple: Transformed SQL and retargeted metadata when the convention
            is configured and matches, the inputs unchanged otherwise
        """
        convention = self.settings.conventions.detail_tables
        if (
            convention is not None
            and metadata.table_name
            and metadata.table_name.endswith(convention.table_suffix)
            and metadata.schema_name == convention.source_schema
        ):
            self.logger.info(
                "Applying silver transformation to Detail table %s.%s",
                metadata.schema_name,
                metadata.table_name,
            )
            transformed_metadata = deepcopy(metadata)
            transformed_metadata.schema_name = convention.target_schema
            # removesuffix, not replace: the suffix is what marks the table,
            # so `DetailOrderDetail` is `DetailOrder`, not `Order`.
            transformed_metadata.table_name = metadata.table_name.removesuffix(
                convention.table_suffix
            )

            return self.transform_detail_to_silver(sql), transformed_metadata

        return sql, metadata

    def transform_detail_to_silver(self, detail_query: str) -> str:
        """
        Transform detail query to include null handling and default row using SQLGlot.

        This method takes a detail table query (like Customer_FactDetail) and transforms it
        to create a silver table directly, applying null handling and adding a default row.

        Args:
            detail_query: The final detail SELECT query from transformation
            table_name: Optional table name for custom default handling

        Returns:
            Transformed SELECT query ready for direct silver table creation

        Example:
            >>> sequencer = SilverTransformationSequencer()
            >>> detail_sql = "SELECT CustomerKey, CreditLimit FROM temp.Stage"
            >>> silver_sql = sequencer.transform_detail_to_silver(detail_sql)
            >>> # Returns query with ISNULL handling and default row
        """
        # Parse the detail query using SQLGlot
        try:
            ast = sqlglot.parse_one(detail_query, dialect=self.sql_dialect)
        except Exception as e:
            raise ValueError(f"Failed to parse SQL query: {e}") from e

        # Find the SELECT clause
        select = ast.find(exp.Select)
        if not select:
            raise ValueError("Could not find SELECT clause in query")

        null_handled_cols = []
        default_values = []

        # Process each column in the SELECT
        for expr in select.expressions:
            # Get column alias (the output column name)
            if isinstance(expr, exp.Alias):
                col_name = expr.alias
                source_expr = expr.this
            elif isinstance(expr, exp.Column):
                col_name = expr.name
                source_expr = expr
            else:
                # Complex expression without alias - generate a name
                col_name = expr.sql(dialect=self.sql_dialect).replace(" ", "_")[:50]
                source_expr = expr

            # Determine null handling based on column name/type
            null_expr, default_val = self._get_null_handling(col_name, source_expr)

            null_handled_cols.append(f"{null_expr} AS [{col_name}]")
            default_values.append(f"{default_val} AS [{col_name}]")

        # Build the transformed query with CTEs
        null_handled_str = ",\n        ".join(null_handled_cols)
        default_values_str = ", ".join(default_values)

        transformed_query = f"""WITH detail_data AS (
                    {detail_query}
                ),
                transformed_data AS (
                    SELECT 
                        {null_handled_str}
                    FROM detail_data
                )
                SELECT * FROM transformed_data
                UNION ALL
                SELECT {default_values_str}"""

        return transformed_query

    def _get_null_handling(self, col_name: str, source_expr: exp.Expression) -> tuple[str, str]:
        """Determine null handling and default value for a column.

        This was an eleven-branch ladder that read a column's *name* to decide
        what its NULLs should become: ``RecID`` to 0, anything ending ``Key``
        to -1, anything ending ``ID`` to -1 or '' depending on whether the name
        contained "status", "credit" or "balance", ``Date`` to 1900-01-01, and
        so on down to an unconditional '' for everything else. Those are one
        warehouse's conventions, so they now come from
        ``conventions.null_handling`` -- an ordered list, first match wins --
        and the shipped default is an empty list: no rule, no rewrite.

        The one branch that stayed is the COALESCE check, which is structural
        rather than conventional: a column the query's author already gave a
        default keeps it. (It never actually fired. sqlglot puts a COALESCE's
        first argument in ``.this`` and only the rest in ``.expressions``, so
        the old ``len(expressions) > 1`` guard was false for the two-argument
        form and ``expressions[1]`` named the *third* argument of the rest.)

        Note: the emitted ``ISNULL(...)`` call and ``[bracket]`` quoting are
        T-SQL, while ``self.sql_dialect`` is configurable and used elsewhere in
        this class. Nothing here consults it. Rendering these through sqlglot
        for the configured dialect is a larger change than this task, and is
        called out rather than half-done.

        Args:
            col_name: Column name/alias
            source_expr: SQLGlot expression for the column

        Returns:
            Tuple of (null_handling_expression, default_value)
        """
        # Already defaulted by the author - don't double-wrap.
        if isinstance(source_expr, exp.Coalesce) and source_expr.expressions:
            default = source_expr.expressions[0].sql(dialect=self.sql_dialect)
            return (f"[{col_name}]", default)

        for rule in self.settings.conventions.null_handling:
            if not rule.matches(col_name):
                continue
            if rule.wrap:
                return (f"ISNULL([{col_name}], {rule.default})", rule.default)
            return (f"[{col_name}]", rule.default)

        # No rule claims this column, so its NULLs are left as NULLs.
        return (f"[{col_name}]", "NULL")
